global:
  scrape_interval: 15s
  # external systems (federation, remote storage, Alertmanager).

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s # overriding for the case of job -> prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # sample job for a node running node_exporter
  # the ‘node_exporter’s within the targets will be the ip’s of the device to be monitored.
  # in this case I am able to use this placeholder is because the components are in the same container environment
  - job_name: "node_exporter"
    static_configs:
      - targets:
          [
            "node_exporter:9100",
            "node_exporter_2:9100",
            "node_exporter_3:9100",
            "192.168.68.121:9100",
          ]

  - job_name: "grok_exporter"
    static_configs:
      - targets: ["grok_exporter:9144"]
